In [ ]:
#pip install -U selenium
from selenium import webdriver
from bs4 import BeautifulSoup
from pprint import pprint
import time
import os
import pandas as pd

# 저장 경로: ../데이터셋 우선, 없으면 ../data
DATA_DIR = "../데이터셋" if os.path.isdir("../데이터셋") else "../data"

In [5]:

# webdriver 실행
dr = webdriver.Chrome()

# target page 접근
dr.get("https://www.starbucks.co.kr/menu/drink_list.do")

# html source 추출
html_source = dr.page_source

# BS로 html parsing
soup = BeautifulSoup(html_source, 'html.parser')

# 원하는 항목의 데이터만 추출
products = soup.select('.product_list dd a')

# 결과 확인
pprint(products)

# 제품 이름, 코드 추출
prod_cd = [[product['prod'], product.find('img')['alt']] for product in products]

# 결과 확인
pprint(prod_cd)

# result를 담을 빈 List 생성
result = []

# 제품별로 for loop
for prod in prod_cd:
    container = dict()
    cd = prod[0]
    name = prod[1]
    dr.get("https://www.starbucks.co.kr/menu/drink_view.do?product_cd={prod_cd}".format(prod_cd=cd))
    html_source = dr.page_source
    soup = BeautifulSoup(html_source, 'html.parser')
    
    # 용량 정보
    volume = soup.select_one('.product_info_head #product_info01').get_text()
    
    # 제품 영양정보
    kcal = soup.select_one('.product_info_content .kcal dd').get_text()
    sat_FAT = soup.select_one('.product_info_content .sat_FAT dd').get_text()
    protein = soup.select_one('.product_info_content .protein dd').get_text()
    fat = soup.select_one('.product_info_content .fat dd').get_text()
    trans_FAT = soup.select_one('.product_info_content .trans_FAT dd').get_text()
    protein = soup.select_one('.product_info_content .protein dd').get_text()
    sodium = soup.select_one('.product_info_content .sodium dd').get_text()
    sugars = soup.select_one('.product_info_content .sugars dd').get_text()
    caffeine = soup.select_one('.product_info_content .caffeine dd').get_text()
    cholesterol = soup.select_one('.product_info_content .cholesterol dd').get_text()
    chabo = soup.select_one('.product_info_content .chabo dd').get_text()
    
    container['cd'] = cd
    container['name'] = name
    container['kcal'] = kcal
    container['sat_FAT'] = sat_FAT
    container['protein'] = protein
    container['fat'] = fat
    container['trans_FAT'] = trans_FAT
    container['protein'] = protein
    container['sodium'] = sodium
    container['sugars'] = sugars
    container['caffeine'] = caffeine
    container['cholesterol'] = cholesterol
    container['chabo'] = chabo
    result.append(container)
    
    # 트래픽 조절을 위해 3초간 pause
    time.sleep(3)

pprint(result)

# DataFrame으로 변환
df = pd.DataFrame(result)

# 데이터 확인
df

[<a class="goDrinkView" href="javascript:void(0)" prod="9200000002487"><img alt="나이트로 바닐라 크림" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000002487]_20250626171201110.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000000479"><img alt="나이트로 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000000479]_20250626095418324.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002081"><img alt="돌체 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000002081]_20250626100020135.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002407"><img alt="리저브 나이트로" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/02/[9200000002407]_20210225095106743.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002093"><img alt="리저브 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/03/[9200000002093]_20240318144604476.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005282"><img alt="막걸리향 크림 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/05/[9200000005282]_20240509131200017.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004312"><img alt="민트 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2022/10/[9200000004312]_20221005145029134.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000000487"><img alt="바닐라 크림 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000000487]_20250626095703208.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005991"><img alt="베르가못 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/11/[9200000005991]_20251125104417629.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006301"><img alt="블랙&amp;화이트 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/07/[9200000006301]_20250703090404091.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006056"><img alt="스모크드 콜드 패션드" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/04/[9200000006056]_20250424105540077.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000003661"><img alt="시그니처 더 블랙 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000003661]_20250626093642415.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004750"><img alt="여수 윤슬 헤이즐넛 콜드브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000004750]_20250626093847094.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000003285"><img alt="오트 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000003285]_20250626095600441.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005616"><img alt="제주 비자림 리저브 콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/10/[9200000005616]_20241014134021881.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000000038"><img alt="콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000000038]_20250626095744182.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004770"><img alt="콜드 브루" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000004770]_20250626175029778.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000001636"><img alt="콜드 브루 몰트" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/02/[9200000001636]_20210225093600536.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000001635"><img alt="콜드 브루 플로트" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/02/[9200000001635]_20210225092236748.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="2"><img alt="브루드 커피 " src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[2]_20210430111934117.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="106509"><img alt="아이스 브루드 커피" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[106509]_20250626092521116.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006655"><img alt="리저브 아이스 프렌즈 시나몬 돌체폼 카푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/12/[9200000006655]_20251216154824521.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006654"><img alt="리저브 프렌즈 시나몬 돌체폼 카푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/12/[9200000006654]_20251216154708061.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006619"><img alt="아이스 프렌즈 시나몬 돌체폼 카푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/12/[9200000006619]_20251216153412094.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006616"><img alt="프렌즈 시나몬 돌체폼 카푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/12/[9200000006616]_20251216153007446.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000003252"><img alt="더블 에스프레소 크림 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/12/[9200000003252]_20251216150524131.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000003255"><img alt="아이스 더블 에스프레소 크림 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/12/[9200000003255]_20251216150646215.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="30"><img alt="에스프레소 콘 파나" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[30]_20210415144252244.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="25"><img alt="에스프레소 마키아또" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[25]_20210415144211211.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005514"><img alt="스타벅스 1호점 카페 아메리카노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/09/[9200000005514]_20240919154516844.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005516"><img alt="아이스 스타벅스 1호점 카페 아메리카노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/09/[9200000005516]_20240919154833807.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110563"><img alt="아이스 카페 아메리카노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110563]_20250626094353711.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="94"><img alt="카페 아메리카노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[94]_20210430103337006.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110582"><img alt="아이스 카라멜 마키아또" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110582]_20250626095111658.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="126197"><img alt="카라멜 마키아또" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[126197]_20210415154609863.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110601"><img alt="아이스 카푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110601]_20250626095213930.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="38"><img alt="카푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[38]_20210415154821846.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004119"><img alt="라벤더 카페 브레베" src="https://image.istarbucks.co.kr/upload/store/skuimg/2022/04/[9200000004119]_20220412083025862.png"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006235"><img alt="밀크카라멜 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000006235]_20250604124942828.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006343"><img alt="바닐라 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/10/[9200000006343]_20251029141705796.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000001939"><img alt="바닐라 빈 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/02/[9200000001939]_20210225094313315.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006054"><img alt="번트 카라멜 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/05/[9200000006054]_20250514142846184.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002095"><img alt="사케라또 비안코 오버 아이스" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/03/[9200000002095]_20240318144701881.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005518"><img alt="스타벅스 1호점 카페 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/09/[9200000005518]_20240919154933695.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005522"><img alt="스타벅스 1호점 크림 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/09/[9200000005522]_20240919155344866.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006164"><img alt="스타벅스 꿀 호떡 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/05/[9200000006164]_20250513101130306.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="128692"><img alt="스타벅스 돌체 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[128692]_20210426091933665.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004120"><img alt="아이스 라벤더 카페 브레베" src="https://image.istarbucks.co.kr/upload/store/skuimg/2022/04/[9200000004120]_20220412082952150.png"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006238"><img alt="아이스 밀크카라멜 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000006238]_20250613084659816.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006346"><img alt="아이스 바닐라 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/10/[9200000006346]_20251029141759604.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000001941"><img alt="아이스 바닐라 빈 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/02/[9200000001941]_20210225094346653.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005520"><img alt="아이스 스타벅스 1호점 카페 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/09/[9200000005520]_20240919155241283.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005523"><img alt="아이스 스타벅스 1호점 크림 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/09/[9200000005523]_20240919155443058.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006165"><img alt="아이스 스타벅스 꿀 호떡 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/05/[9200000006165]_20250513101211857.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="128695"><img alt="아이스 스타벅스 돌체 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[128695]_20250626095651684.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005285"><img alt="아이스 인절미 크림 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/05/[9200000005285]_20240509131125335.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110569"><img alt="아이스 카페 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110569]_20250626094801903.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005284"><img alt="인절미 크림 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/05/[9200000005284]_20240509131037171.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006575"><img alt="제주 비자림 리저브 에스프레소 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/10/[9200000006575]_20251013103821201.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="41"><img alt="카페 라떼" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[41]_20210415133833725.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006338"><img alt="코르타도" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/10/[9200000006338]_20251029141124907.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110566"><img alt="아이스 카페 모카" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110566]_20250626113005628.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110572"><img alt="아이스 화이트 초콜릿 모카" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110572]_20250626113205748.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="46"><img alt="카페 모카" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[46]_20210415134438165.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004313"><img alt="클래식 민트 모카" src="https://image.istarbucks.co.kr/upload/store/skuimg/2022/10/[9200000004313]_20221005145156959.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="128192"><img alt="화이트 초콜릿 모카" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[128192]_20210415155639126.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005181"><img alt="아이스 플랫 화이트" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000005181]_20250626095819133.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005178"><img alt="플랫 화이트" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/03/[9200000005178]_20240326103727795.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110612"><img alt="바닐라 스타벅스 더블 샷" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110612]_20250626095701777.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000003505"><img alt="사케라또 아포가토" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/03/[9200000003505]_20210322093241535.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000003506"><img alt="스파클링 시트러스 에스프레소" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/03/[9200000003506]_20210322093317854.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="20"><img alt="에스프레소" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/04/[20]_20210415144112678.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9900000001604"><img alt="에스프레소 플라이트" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/09/[9900000001604]_20240909104819181.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9900000001721"><img alt="에스프레소 플라이트 도산" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/04/[9900000001721]_20250424124232037.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110611"><img alt="커피 스타벅스 더블 샷" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110611]_20250626095539402.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000001631"><img alt="클래식 아포가토" src="https://image.istarbucks.co.kr/upload/store/skuimg/2021/02/[9200000001631]_20210225090916684.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="110614"><img alt="헤이즐넛 스타벅스 더블 샷" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[110614]_20250626174624137.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006593"><img alt="바나나 마카다미아 오트 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/11/[9200000006593]_20251112142011730.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006594"><img alt="초코 바나나 마카다미아 오트 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/11/[9200000006594]_20251112142046388.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002760"><img alt="더블 에스프레소 칩 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000002760]_20250626095415811.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006303"><img alt="스타벅스 꿀 호떡 크림 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000006303]_20250619133012310.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="168007"><img alt="에스프레소 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[168007]_20250626095952087.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="168016"><img alt="자바 칩 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[168016]_20250626113600873.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="168010"><img alt="카라멜 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[168010]_20250626113443023.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005369"><img alt="딸기 글레이즈드 크림 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2024/06/[9200000005369]_20240614143554454.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006304"><img alt="베르가못 딸기 크림 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/07/[9200000006304]_20250708105445804.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000006305"><img alt="베르가못 제주 말차 크림 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000006305]_20250619141412982.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005782"><img alt="인절미 제주 말차 크림 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000005782]_20250626114430130.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002088"><img alt="제주 까망 크림 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000002088]_20250626114629418.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002502"><img alt="제주 말차 크림 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000002502]_20250626100915378.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002090"><img alt="제주 쑥떡 크림 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000002090]_20250626114614395.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="168066"><img alt="초콜릿 크림 칩 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[168066]_20250626113822018.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000002403"><img alt="화이트 타이거 프라푸치노" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[9200000002403]_20250626100106311.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="167004"><img alt="망고 패션 프루트 블렌디드" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/06/[167004]_20250626095805229.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004716"><img alt="북한산 레몬 얼 그레이 블렌디드" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/10/[9200000004716]_20251029080615246.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004945"><img alt="스타벅스 클래식 밀크티 블렌디드" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/08/[9200000004945]_20250827131549415.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000004870"><img alt="여수 바다 유자 블렌디드" src="https://image.istarbucks.co.kr/upload/store/skuimg/2023/09/[9200000004870]_20230905110300360.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000005377"><img alt="제주 탄제린 블렌디드" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/10/[9200000005377]_20251013104535651.jpg"/></a>,
 <a class="goDrinkView" href="javascript:void(0)" prod="9200000003276"><img alt="딸기 딜라이트 요거트 블렌디드" src="https://image.istarbucks.co.kr/upload/store/skuimg/2025/07/[9200000003276]_20250721084027663.jpg"/></a>,

[{'caffeine': '232',
  'cd': '9200000002487',
  'chabo': '10',
  'cholesterol': '5',
  'fat': '2.7',
  'kcal': '80',
  'name': '나이트로 바닐라 크림',
  'protein': '1',
  'sat_FAT': '2',
  'sodium': '40',
  'sugars': '10',
  'trans_FAT': '0'},
 {'caffeine': '245',
  'cd': '9200000000479',
  'chabo': '0',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '5',
  'name': '나이트로 콜드 브루',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '5',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '155',
  'cd': '9200000002081',
  'chabo': '24',
  'cholesterol': '20',
  'fat': '10',
  'kcal': '220',
  'name': '돌체 콜드 브루',
  'protein': '6',
  'sat_FAT': '6',
  'sodium': '80',
  'sugars': '22',
  'trans_FAT': '0'},
 {'caffeine': '190',
  'cd': '9200000002407',
  'chabo': '0',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '5',
  'name': '리저브 나이트로',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '0',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '190',
  'cd': '9200000002093',
  'chabo': '0',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '5',
  'name': '리저브 콜드 브루',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '0',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '53',
  'cd': '9200000005282',
  'chabo': '35',
  'cholesterol': '10',
  'fat': '16',
  'kcal': '300',
  'name': '막걸리향 크림 콜드 브루',
  'protein': '3',
  'sat_FAT': '13',
  'sodium': '65',
  'sugars': '32',
  'trans_FAT': '0'},
 {'caffeine': '415',
  'cd': '9200000004312',
  'chabo': '24',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '100',
  'name': '민트 콜드 브루',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '0',
  'sugars': '23',
  'trans_FAT': '0'},
 {'caffeine': '155',
  'cd': '9200000000487',
  'chabo': '11',
  'cholesterol': '10',
  'fat': '8',
  'kcal': '125',
  'name': '바닐라 크림 콜드 브루',
  'protein': '3',
  'sat_FAT': '6',
  'sodium': '58',
  'sugars': '11',
  'trans_FAT': '0'},
 {'caffeine': '90',
  'cd': '9200000005991',
  'chabo': '22',
  'cholesterol': '10',
  'fat': '2.9',
  'kcal': '125',
  'name': '베르가못 콜드 브루',
  'protein': '3',
  'sat_FAT': '1.7',
  'sodium': '45',
  'sugars': '22',
  'trans_FAT': '0'},
 {'caffeine': '190',
  'cd': '9200000006301',
  'chabo': '12',
  'cholesterol': '5',
  'fat': '14',
  'kcal': '175',
  'name': '블랙&화이트 콜드 브루',
  'protein': '1',
  'sat_FAT': '12',
  'sodium': '70',
  'sugars': '12',
  'trans_FAT': '0'},
 {'caffeine': '135',
  'cd': '9200000006056',
  'chabo': '5',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '30',
  'name': '스모크드 콜드 패션드',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '0',
  'sugars': '6',
  'trans_FAT': '0'},
 {'caffeine': '680',
  'cd': '9200000003661',
  'chabo': '0',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '25',
  'name': '시그니처 더 블랙 콜드 브루',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '50',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '53',
  'cd': '9200000004750',
  'chabo': '28',
  'cholesterol': '15',
  'fat': '12',
  'kcal': '240',
  'name': '여수 윤슬 헤이즐넛 콜드브루',
  'protein': '5',
  'sat_FAT': '9',
  'sodium': '80',
  'sugars': '27',
  'trans_FAT': '0'},
 {'caffeine': '65',
  'cd': '9200000003285',
  'chabo': '20',
  'cholesterol': '0',
  'fat': '3.6',
  'kcal': '120',
  'name': '오트 콜드 브루',
  'protein': '1',
  'sat_FAT': '0.3',
  'sodium': '95',
  'sugars': '14',
  'trans_FAT': '0'},
 {'caffeine': '250',
  'cd': '9200000005616',
  'chabo': '28',
  'cholesterol': '20',
  'fat': '7',
  'kcal': '205',
  'name': '제주 비자림 리저브 콜드 브루',
  'protein': '8',
  'sat_FAT': '4.1',
  'sodium': '100',
  'sugars': '26',
  'trans_FAT': '0'},
 {'caffeine': '155',
  'cd': '9200000000038',
  'chabo': '0',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '5',
  'name': '콜드 브루',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '11',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '360',
  'cd': '9200000004770',
  'chabo': '0',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '5',
  'name': '콜드 브루',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '25',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '190',
  'cd': '9200000001636',
  'chabo': '51',
  'cholesterol': '40',
  'fat': '30',
  'kcal': '505',
  'name': '콜드 브루 몰트',
  'protein': '7',
  'sat_FAT': '20',
  'sodium': '150',
  'sugars': '41',
  'trans_FAT': '0'},
 {'caffeine': '190',
  'cd': '9200000001635',
  'chabo': '21',
  'cholesterol': '20',
  'fat': '15',
  'kcal': '225',
  'name': '콜드 브루 플로트',
  'protein': '3',
  'sat_FAT': '10',
  'sodium': '70',
  'sugars': '18',
  'trans_FAT': '0'},
 {'caffeine': '260',
  'cd': '2',
  'chabo': '0',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '5',
  'name': '브루드 커피 ',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '15',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '140',
  'cd': '106509',
  'chabo': '0',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '5',
  'name': '아이스 브루드 커피',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '10',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000006655',
  'chabo': '31',
  'cholesterol': '20',
  'fat': '9',
  'kcal': '230',
  'name': '리저브 아이스 프렌즈 시나몬 돌체폼 카푸치노',
  'protein': '6',
  'sat_FAT': '6',
  'sodium': '95',
  'sugars': '26',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000006654',
  'chabo': '33',
  'cholesterol': '25',
  'fat': '11',
  'kcal': '265',
  'name': '리저브 프렌즈 시나몬 돌체폼 카푸치노',
  'protein': '8',
  'sat_FAT': '7',
  'sodium': '120',
  'sugars': '29',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000006619',
  'chabo': '31',
  'cholesterol': '20',
  'fat': '9',
  'kcal': '230',
  'name': '아이스 프렌즈 시나몬 돌체폼 카푸치노',
  'protein': '6',
  'sat_FAT': '6',
  'sodium': '95',
  'sugars': '26',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000006616',
  'chabo': '33',
  'cholesterol': '25',
  'fat': '11',
  'kcal': '265',
  'name': '프렌즈 시나몬 돌체폼 카푸치노',
  'protein': '8',
  'sat_FAT': '7',
  'sodium': '120',
  'sugars': '29',
  'trans_FAT': '0'},
 {'caffeine': '90',
  'cd': '9200000003252',
  'chabo': '25',
  'cholesterol': '25',
  'fat': '12',
  'kcal': '240',
  'name': '더블 에스프레소 크림 라떼',
  'protein': '8',
  'sat_FAT': '8',
  'sodium': '120',
  'sugars': '24',
  'trans_FAT': '0'},
 {'caffeine': '90',
  'cd': '9200000003255',
  'chabo': '21',
  'cholesterol': '15',
  'fat': '9',
  'kcal': '190',
  'name': '아이스 더블 에스프레소 크림 라떼',
  'protein': '5',
  'sat_FAT': '7',
  'sodium': '85',
  'sugars': '20',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '30',
  'chabo': '1',
  'cholesterol': '0',
  'fat': '2.4',
  'kcal': '30',
  'name': '에스프레소 콘 파나',
  'protein': '1',
  'sat_FAT': '2',
  'sodium': '5',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '25',
  'chabo': '1',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '10',
  'name': '에스프레소 마키아또',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '0',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000005514',
  'chabo': '2',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '10',
  'name': '스타벅스 1호점 카페 아메리카노',
  'protein': '1',
  'sat_FAT': '0',
  'sodium': '0',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000005516',
  'chabo': '2',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '10',
  'name': '아이스 스타벅스 1호점 카페 아메리카노',
  'protein': '1',
  'sat_FAT': '0',
  'sodium': '0',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '150',
  'cd': '110563',
  'chabo': '2',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '10',
  'name': '아이스 카페 아메리카노',
  'protein': '1',
  'sat_FAT': '0',
  'sodium': '5',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '150',
  'cd': '94',
  'chabo': '2',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '10',
  'name': '카페 아메리카노',
  'protein': '1',
  'sat_FAT': '0',
  'sodium': '5',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '110582',
  'chabo': '23',
  'cholesterol': '20',
  'fat': '8',
  'kcal': '190',
  'name': '아이스 카라멜 마키아또',
  'protein': '6',
  'sat_FAT': '4.6',
  'sodium': '110',
  'sugars': '22',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '126197',
  'chabo': '24',
  'cholesterol': '25',
  'fat': '9',
  'kcal': '200',
  'name': '카라멜 마키아또',
  'protein': '8',
  'sat_FAT': '5',
  'sodium': '130',
  'sugars': '22',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '110601',
  'chabo': '10',
  'cholesterol': '20',
  'fat': '6',
  'kcal': '110',
  'name': '아이스 카푸치노',
  'protein': '6',
  'sat_FAT': '3.5',
  'sodium': '90',
  'sugars': '9',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '38',
  'chabo': '9',
  'cholesterol': '15',
  'fat': '6',
  'kcal': '110',
  'name': '카푸치노',
  'protein': '6',
  'sat_FAT': '3',
  'sodium': '70',
  'sugars': '8',
  'trans_FAT': '0'},
 {'caffeine': '105',
  'cd': '9200000004119',
  'chabo': '31',
  'cholesterol': '25',
  'fat': '27',
  'kcal': '400',
  'name': '라벤더 카페 브레베',
  'protein': '8',
  'sat_FAT': '22',
  'sodium': '140',
  'sugars': '30',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000006235',
  'chabo': '31',
  'cholesterol': '25',
  'fat': '17',
  'kcal': '310',
  'name': '밀크카라멜 라떼',
  'protein': '8',
  'sat_FAT': '13',
  'sodium': '280',
  'sugars': '22',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000006343',
  'chabo': '25',
  'cholesterol': '25',
  'fat': '9',
  'kcal': '210',
  'name': '바닐라 라떼',
  'protein': '8',
  'sat_FAT': '5',
  'sodium': '130',
  'sugars': '24',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000001939',
  'chabo': '29',
  'cholesterol': '30',
  'fat': '9',
  'kcal': '245',
  'name': '바닐라 빈 라떼',
  'protein': '9',
  'sat_FAT': '6',
  'sodium': '150',
  'sugars': '27',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000006054',
  'chabo': '37',
  'cholesterol': '35',
  'fat': '20',
  'kcal': '380',
  'name': '번트 카라멜 라떼',
  'protein': '12',
  'sat_FAT': '13',
  'sodium': '250',
  'sugars': '30',
  'trans_FAT': '0'},
 {'caffeine': '315',
  'cd': '9200000002095',
  'chabo': '17',
  'cholesterol': '10',
  'fat': '21',
  'kcal': '270',
  'name': '사케라또 비안코 오버 아이스',
  'protein': '3',
  'sat_FAT': '18',
  'sodium': '45',
  'sugars': '14',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000005518',
  'chabo': '17',
  'cholesterol': '30',
  'fat': '10',
  'kcal': '200',
  'name': '스타벅스 1호점 카페 라떼',
  'protein': '10',
  'sat_FAT': '6',
  'sodium': '150',
  'sugars': '15',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000005522',
  'chabo': '20',
  'cholesterol': '5',
  'fat': '14',
  'kcal': '215',
  'name': '스타벅스 1호점 크림 라떼',
  'protein': '2',
  'sat_FAT': '12',
  'sodium': '25',
  'sugars': '19',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000006164',
  'chabo': '45',
  'cholesterol': '30',
  'fat': '18',
  'kcal': '360',
  'name': '스타벅스 꿀 호떡 라떼',
  'protein': '10',
  'sat_FAT': '11',
  'sodium': '150',
  'sugars': '23',
  'trans_FAT': '0'},
 {'caffeine': '150',
  'cd': '128692',
  'chabo': '34',
  'cholesterol': '10',
  'fat': '3.1',
  'kcal': '215',
  'name': '스타벅스 돌체 라떼',
  'protein': '12',
  'sat_FAT': '2',
  'sodium': '190',
  'sugars': '32',
  'trans_FAT': '0'},
 {'caffeine': '105',
  'cd': '9200000004120',
  'chabo': '28',
  'cholesterol': '20',
  'fat': '22',
  'kcal': '335',
  'name': '아이스 라벤더 카페 브레베',
  'protein': '6',
  'sat_FAT': '18',
  'sodium': '110',
  'sugars': '27',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000006238',
  'chabo': '26',
  'cholesterol': '15',
  'fat': '13',
  'kcal': '240',
  'name': '아이스 밀크카라멜 라떼',
  'protein': '5',
  'sat_FAT': '10',
  'sodium': '220',
  'sugars': '17',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000006346',
  'chabo': '20',
  'cholesterol': '15',
  'fat': '5',
  'kcal': '150',
  'name': '아이스 바닐라 라떼',
  'protein': '5',
  'sat_FAT': '3.2',
  'sodium': '80',
  'sugars': '19',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000001941',
  'chabo': '22',
  'cholesterol': '15',
  'fat': '4.8',
  'kcal': '155',
  'name': '아이스 바닐라 빈 라떼',
  'protein': '5',
  'sat_FAT': '2.9',
  'sodium': '75',
  'sugars': '20',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000005520',
  'chabo': '10',
  'cholesterol': '15',
  'fat': '5',
  'kcal': '110',
  'name': '아이스 스타벅스 1호점 카페 라떼',
  'protein': '6',
  'sat_FAT': '3.2',
  'sodium': '80',
  'sugars': '8',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000005523',
  'chabo': '20',
  'cholesterol': '5',
  'fat': '14',
  'kcal': '215',
  'name': '아이스 스타벅스 1호점 크림 라떼',
  'protein': '2',
  'sat_FAT': '12',
  'sodium': '25',
  'sugars': '19',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000006165',
  'chabo': '38',
  'cholesterol': '15',
  'fat': '16',
  'kcal': '290',
  'name': '아이스 스타벅스 꿀 호떡 라떼',
  'protein': '6',
  'sat_FAT': '10',
  'sodium': '80',
  'sugars': '16',
  'trans_FAT': '0'},
 {'caffeine': '150',
  'cd': '128695',
  'chabo': '30',
  'cholesterol': '10',
  'fat': '3.1',
  'kcal': '190',
  'name': '아이스 스타벅스 돌체 라떼',
  'protein': '10',
  'sat_FAT': '2',
  'sodium': '140',
  'sugars': '28',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000005285',
  'chabo': '53',
  'cholesterol': '15',
  'fat': '23',
  'kcal': '455',
  'name': '아이스 인절미 크림 라떼',
  'protein': '9',
  'sat_FAT': '16',
  'sodium': '180',
  'sugars': '43',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '110569',
  'chabo': '9',
  'cholesterol': '20',
  'fat': '6',
  'kcal': '110',
  'name': '아이스 카페 라떼',
  'protein': '6',
  'sat_FAT': '3.5',
  'sodium': '75',
  'sugars': '8',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '9200000005284',
  'chabo': '59',
  'cholesterol': '25',
  'fat': '27',
  'kcal': '530',
  'name': '인절미 크림 라떼',
  'protein': '12',
  'sat_FAT': '19',
  'sodium': '250',
  'sugars': '49',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000006575',
  'chabo': '26',
  'cholesterol': '30',
  'fat': '10',
  'kcal': '240',
  'name': '제주 비자림 리저브 에스프레소 라떼',
  'protein': '10',
  'sat_FAT': '7',
  'sodium': '160',
  'sugars': '22',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '41',
  'chabo': '14',
  'cholesterol': '30',
  'fat': '9',
  'kcal': '180',
  'name': '카페 라떼',
  'protein': '10',
  'sat_FAT': '5',
  'sodium': '115',
  'sugars': '13',
  'trans_FAT': '0'},
 {'caffeine': '255',
  'cd': '9200000006338',
  'chabo': '11',
  'cholesterol': '15',
  'fat': '5',
  'kcal': '115',
  'name': '코르타도',
  'protein': '6',
  'sat_FAT': '3.2',
  'sodium': '85',
  'sugars': '8',
  'trans_FAT': '0'},
 {'caffeine': '95',
  'cd': '110566',
  'chabo': '28',
  'cholesterol': '45',
  'fat': '14',
  'kcal': '250',
  'name': '아이스 카페 모카',
  'protein': '7',
  'sat_FAT': '8',
  'sodium': '70',
  'sugars': '21',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '110572',
  'chabo': '32',
  'cholesterol': '20',
  'fat': '16',
  'kcal': '300',
  'name': '아이스 화이트 초콜릿 모카',
  'protein': '8',
  'sat_FAT': '10',
  'sodium': '150',
  'sugars': '31',
  'trans_FAT': '0'},
 {'caffeine': '95',
  'cd': '46',
  'chabo': '33',
  'cholesterol': '45',
  'fat': '15',
  'kcal': '290',
  'name': '카페 모카',
  'protein': '10',
  'sat_FAT': '9',
  'sodium': '105',
  'sugars': '25',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000004313',
  'chabo': '62',
  'cholesterol': '0',
  'fat': '8',
  'kcal': '335',
  'name': '클래식 민트 모카',
  'protein': '4',
  'sat_FAT': '0.7',
  'sodium': '200',
  'sugars': '43',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '128192',
  'chabo': '38',
  'cholesterol': '30',
  'fat': '18',
  'kcal': '350',
  'name': '화이트 초콜릿 모카',
  'protein': '11',
  'sat_FAT': '10',
  'sodium': '200',
  'sugars': '37',
  'trans_FAT': '0'},
 {'caffeine': '130',
  'cd': '9200000005181',
  'chabo': '11',
  'cholesterol': '20',
  'fat': '6',
  'kcal': '120',
  'name': '아이스 플랫 화이트',
  'protein': '6',
  'sat_FAT': '3.5',
  'sodium': '90',
  'sugars': '9',
  'trans_FAT': '0'},
 {'caffeine': '130',
  'cd': '9200000005178',
  'chabo': '15',
  'cholesterol': '25',
  'fat': '8',
  'kcal': '170',
  'name': '플랫 화이트',
  'protein': '8',
  'sat_FAT': '5',
  'sodium': '130',
  'sugars': '13',
  'trans_FAT': '0'},
 {'caffeine': '150',
  'cd': '110612',
  'chabo': '16',
  'cholesterol': '5',
  'fat': '6',
  'kcal': '125',
  'name': '바닐라 스타벅스 더블 샷',
  'protein': '2',
  'sat_FAT': '4.5',
  'sodium': '30',
  'sugars': '14',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000003505',
  'chabo': '36',
  'cholesterol': '20',
  'fat': '15',
  'kcal': '290',
  'name': '사케라또 아포가토',
  'protein': '4',
  'sat_FAT': '10',
  'sodium': '70',
  'sugars': '30',
  'trans_FAT': '0'},
 {'caffeine': '105',
  'cd': '9200000003506',
  'chabo': '16',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '65',
  'name': '스파클링 시트러스 에스프레소',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '5',
  'sugars': '15',
  'trans_FAT': '0'},
 {'caffeine': '75',
  'cd': '20',
  'chabo': '1',
  'cholesterol': '0',
  'fat': '0',
  'kcal': '5',
  'name': '에스프레소',
  'protein': '0',
  'sat_FAT': '0',
  'sodium': '0',
  'sugars': '0',
  'trans_FAT': '0'},
 {'caffeine': '-',
  'cd': '9900000001604',
  'chabo': '-',
  'cholesterol': '-',
  'fat': '-',
  'kcal': '-',
  'name': '에스프레소 플라이트',
  'protein': '-',
  'sat_FAT': '-',
  'sodium': '-',
  'sugars': '-',
  'trans_FAT': '-'},
 {'caffeine': '-',
  'cd': '9900000001721',
  'chabo': '-',
  'cholesterol': '-',
  'fat': '-',
  'kcal': '-',
  'name': '에스프레소 플라이트 도산',
  'protein': '-',
  'sat_FAT': '-',
  'sodium': '-',
  'sugars': '-',
  'trans_FAT': '-'},
 {'caffeine': '150',
  'cd': '110611',
  'chabo': '16',
  'cholesterol': '5',
  'fat': '6',
  'kcal': '125',
  'name': '커피 스타벅스 더블 샷',
  'protein': '2',
  'sat_FAT': '4.5',
  'sodium': '30',
  'sugars': '14',
  'trans_FAT': '0'},
 {'caffeine': '210',
  'cd': '9200000001631',
  'chabo': '23',
  'cholesterol': '20',
  'fat': '15',
  'kcal': '240',
  'name': '클래식 아포가토',
  'protein': '4',
  'sat_FAT': '10',
  'sodium': '70',
  'sugars': '18',
  'trans_FAT': '0'},
 {'caffeine': '150',
  'cd': '110614',
  'chabo': '16',
  'cholesterol': '5',
  'fat': '6',
  'kcal': '125',
  'name': '헤이즐넛 스타벅스 더블 샷',
  'protein': '2',
  'sat_FAT': '4.5',
  'sodium': '30',
  'sugars': '14',
  'trans_FAT': '0'},
 {'caffeine': '0',
  'cd': '9200000006593',
  'chabo': '62',
  'cholesterol': '0',
  'fat': '6',
  'kcal': '330',
  'name': '바나나 마카다미아 오트 프라푸치노',
  'protein': '3',
  'sat_FAT': '0.9',
  'sodium': '350',
  'sugars': '46',
  'trans_FAT': '0'},
 {'caffeine': '5',
  'cd': '9200000006594',
  'chabo': '61',
  'cholesterol': '0',
  'fat': '5',
  'kcal': '325',
  'name': '초코 바나나 마카다미아 오트 프라푸치노',
  'protein': '3',
  'sat_FAT': '0.7',
  'sodium': '350',
  'sugars': '45',
  'trans_FAT': '0'},
 {'caffeine': '130',
  'cd': '9200000002760',
  'chabo': '23',
  'cholesterol': '10',
  'fat': '16',
  'kcal': '225',
  'name': '더블 에스프레소 칩 프라푸치노',
  'protein': '4',
  'sat_FAT': '13',
  'sodium': '170',
  'sugars': '18',
  'trans_FAT': '0'},
 {'caffeine': '0',
  'cd': '9200000006303',
  'chabo': '47',
  'cholesterol': '15',
  'fat': '15',
  'kcal': '325',
  'name': '스타벅스 꿀 호떡 크림 프라푸치노',
  'protein': '6',
  'sat_FAT': '10',
  'sodium': '180',
  'sugars': '26',
  'trans_FAT': '0'},
 {'caffeine': '120',
  'cd': '168007',
  'chabo': '21',
  'cholesterol': '5',
  'fat': '1.7',
  'kcal': '110',
  'name': '에스프레소 프라푸치노',
  'protein': '2',
  'sat_FAT': '1.1',
  'sodium': '150',
  'sugars': '17',
  'trans_FAT': '0'},
 {'caffeine': '100',
  'cd': '168016',
  'chabo': '40',
  'cholesterol': '10',
  'fat': '12',
  'kcal': '285',
  'name': '자바 칩 프라푸치노',
  'protein': '5',
  'sat_FAT': '6',
  'sodium': '180',
  'sugars': '30',
  'trans_FAT': '0'},
 {'caffeine': '85',
  'cd': '168010',
  'chabo': '28',
  'cholesterol': '10',
  'fat': '10',
  'kcal': '225',
  'name': '카라멜 프라푸치노',
  'protein': '3',
  'sat_FAT': '8',
  'sodium': '180',
  'sugars': '24',
  'trans_FAT': '0'},
 {'caffeine': '5',
  'cd': '9200000005369',
  'chabo': '52',
  'cholesterol': '30',
  'fat': '12',
  'kcal': '315',
  'name': '딸기 글레이즈드 크림 프라푸치노',
  'protein': '5',
  'sat_FAT': '9',
  'sodium': '250',
  'sugars': '37',
  'trans_FAT': '0'},
 {'caffeine': '0',
  'cd': '9200000006304',
  'chabo': '62',
  'cholesterol': '15',
  'fat': '17',
  'kcal': '420',
  'name': '베르가못 딸기 크림 프라푸치노',
  'protein': '5',
  'sat_FAT': '13',

,cd,name,kcal,sat_FAT,protein,fat,trans_FAT,sodium,sugars,caffeine,cholesterol,chabo
0,9200000002487,나이트로 바닐라 크림,80,2,1,2.7,0,40,10,232,5,10
1,9200000000479,나이트로 콜드 브루,5,0,0,0,0,5,0,245,0,0
2,9200000002081,돌체 콜드 브루,220,6,6,10,0,80,22,155,20,24
3,9200000002407,리저브 나이트로,5,0,0,0,0,0,0,190,0,0
4,9200000002093,리저브 콜드 브루,5,0,0,0,0,0,0,190,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
190,9200000003255,아이스 더블 에스프레소 크림 라떼,190,7,5,9,0,85,20,90,15,21
191,9200000006643,아이스 프렌즈 얼 그레이 베리 티 라떼,280,12,4,15,0,60,26,30,15,33
192,9200000006640,프렌즈 얼 그레이 베리 티 라떼,280,12,4,15,0,60,26,30,15,33
193,9200000006646,유자 배 캐모마일 티,190,0,0,0.2,0,0,33,0,0,52
194,9200000006649,아이스 유자 배 캐모마일 티,130,0,0,0.1,0,0,24,0,0,36

In [6]:
df

,cd,name,kcal,sat_FAT,protein,fat,trans_FAT,sodium,sugars,caffeine,cholesterol,chabo
0,9200000002487,나이트로 바닐라 크림,80,2,1,2.7,0,40,10,232,5,10
1,9200000000479,나이트로 콜드 브루,5,0,0,0,0,5,0,245,0,0
2,9200000002081,돌체 콜드 브루,220,6,6,10,0,80,22,155,20,24
3,9200000002407,리저브 나이트로,5,0,0,0,0,0,0,190,0,0
4,9200000002093,리저브 콜드 브루,5,0,0,0,0,0,0,190,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
190,9200000003255,아이스 더블 에스프레소 크림 라떼,190,7,5,9,0,85,20,90,15,21
191,9200000006643,아이스 프렌즈 얼 그레이 베리 티 라떼,280,12,4,15,0,60,26,30,15,33
192,9200000006640,프렌즈 얼 그레이 베리 티 라떼,280,12,4,15,0,60,26,30,15,33
193,9200000006646,유자 배 캐모마일 티,190,0,0,0.2,0,0,33,0,0,52
194,9200000006649,아이스 유자 배 캐모마일 티,130,0,0,0.1,0,0,24,0,0,36

In [7]:
df.columns=('제품코드','제품명','1회 제공량(kcal)','포화지방(g)','단백질(g)','지방(g)','트랜스지방(g)','나트륨(mg)','당류(g)','카페인(mg)','콜레스테롤(mg)','탄수화물(g)')

In [8]:
df

,제품코드,제품명,1회 제공량(kcal),포화지방(g),단백질(g),지방(g),트랜스지방(g),나트륨(mg),당류(g),카페인(mg),콜레스테롤(mg),탄수화물(g)
0,9200000002487,나이트로 바닐라 크림,80,2,1,2.7,0,40,10,232,5,10
1,9200000000479,나이트로 콜드 브루,5,0,0,0,0,5,0,245,0,0
2,9200000002081,돌체 콜드 브루,220,6,6,10,0,80,22,155,20,24
3,9200000002407,리저브 나이트로,5,0,0,0,0,0,0,190,0,0
4,9200000002093,리저브 콜드 브루,5,0,0,0,0,0,0,190,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
190,9200000003255,아이스 더블 에스프레소 크림 라떼,190,7,5,9,0,85,20,90,15,21
191,9200000006643,아이스 프렌즈 얼 그레이 베리 티 라떼,280,12,4,15,0,60,26,30,15,33
192,9200000006640,프렌즈 얼 그레이 베리 티 라떼,280,12,4,15,0,60,26,30,15,33
193,9200000006646,유자 배 캐모마일 티,190,0,0,0.2,0,0,33,0,0,52
194,9200000006649,아이스 유자 배 캐모마일 티,130,0,0,0.1,0,0,24,0,0,36

In [9]:
df.to_csv(os.path.join(DATA_DIR, 'starbucks_menu_260112.csv'), encoding='utf-8-sig')